title: Last Interactive
author: rafaelcolladojr
subtitle: "A two-person studio in Brooklyn making mobile applications and games. Since 2019."

url: "https://lastinteractive.com"
baseurl: ""

# profile-picture: assets/profile.png
# favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/

highlighter: rouge

navbar:
  - name: "Works"
    link: "#works"
  - name: "Studio"
    link: "#studio"

email: "hello@lastinteractive.com"

github: "https://github.com/lastinteractive"
x: "https://x.com/lastinteractive"
instagram: "https://instagram.com/lastinteractive"

# Works
collections:
  works:
    output: true
